
# VIP OPIS
vipopis: §C[==========§eVIP§c==========]
Otrzymuje:
Wyślij SMS'a:
§c[==========§eVIP§c==========]

# SUPERVIP OPIS
svipopis: §C[==========§eSVIP§c==========]
Otrzymuje:
Wyślij SMS'a:
§C[==========§eSVIP§c==========]
# ULTRAVIP OPIS
uvipopis: §C[==========§UVIP§c==========]
Otrzymuje:
Wyślij SMS'a:
§C[==========§eUVIP§c==========]

# YOUTUBE OPIS
ytopis: §C[==========§cYou§fTube§c==========]
Otrzymuje:
Co musisz zrobic?:
§C[==========§cYou§fTube§c==========]
# REGULAMIN OPIS
regulaminopis: §C[==========§4REGULAMIN§c==========]
1:
2:
3:
§C[==========§4REGULAMIN§c==========]
